version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            curl -o packages-microsoft-prod.deb https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
            sudo dpkg -i packages-microsoft-prod.deb

            sudo apt-get update && sudo apt-get install -y --no-install-recommends \
                apt-utils \
                ca-certificates \
                curl \
                apt-transport-https \
                locales \
                git \
                powershell

      - run:
          name: install powershell
          command: |
            echo "run tests"
            

